### ISSUE TITLE
Kagane: "Unable to decrypt data" error after yesterday's Kagane website maintenance

### ISSUE THREAD

**Issue by REFLEXGAMING007** [keiyoushi/tachiyomi-extensions-source#11940]
### Source information

Kagane 1.4.12

### Source language

English

### Steps to reproduce

Open any chapter of any webtoon in the Kagane extension in Mihon/Aniyomi/others 

### Expected behavior

It should load the chapter images 

### Actual behavior

It shows "unable to decrypt data" 

![Image](https://github.com/user-attachments/assets/5f7c9357-be5d-43ab-939e-efd9841e2f7c)

### Mihon/Tachiyomi version

Mihon Stable 0.19.3

### Android version

Android 12

### Other details

This issue started happening right after yesterday’s Kagane website maintenance.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
Duplicate of #11281

This was already reported before. Learn to actually search the existing requests first (both open & closed) before creating a new request. Don't confirm the acknowledgments that you did when you clearly didn't.

**Comment by REFLEXGAMING007** [comment]
No no this is different... It was working yesterday.

Those issues were for older versions which were already solved long ago

**Comment by Smol-Ame** [comment]
It's still the same issue, and it can occur on any page/chapter/entry. Go to your app's Settings > Data and storage, and hit "Clear chapter cache" to see if it helps. Otherwise, the issue exists and the request is open & still applies, wait patiently for a fix or migrate to a different source.

**Comment by REFLEXGAMING007** [comment]
I knew it would get rejected due to duplicate that's why I clearly added that it started happening again right after yesterday's Kagane website maintenance

**Comment by REFLEXGAMING007** [comment]
Deleting chapter caches didn't work either

**Comment by REFLEXGAMING007** [comment]
Man... This is the only source which provided highest image quality manhwa 😞

**Comment by Smol-Ame** [comment]
After discussion with a contributor from earlier to now, seems like the site did change something overall that the extension can't handle. See/subscribe to #11942 if you want updates about this issue.
