### ISSUE TITLE
Demon Sect - HTTP 404 error

### ISSUE THREAD

**Issue by nomaxsnx** [keiyoushi/tachiyomi-extensions-source#592]
### Source information

Demon sect - 1.4.37

### Source language

Português

### Steps to reproduce

1 - Install extension Demon sect (portugues)
2 - Open extension Demon sect (portugues)

### Expected behavior

![1706127147831](https://github.com/keiyoushi/extensions-source/assets/157644160/7959aa9b-a41d-4718-91a2-fc461fe85279)

### Actual behavior

Showing error 404

obs: WebView it's work normal

### Tachiyomi version

0.16.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
likely fixed in #1292

**Comment by nomaxsnx** [comment]
> likely fixed in #1292

![Screenshot_2024-02-20-17-32-22-586_app mihon](https://github.com/keiyoushi/extensions-source/assets/157644160/048b949b-d73a-47b2-a419-1254dcf83932)

Note: I've updated the extension, but I still get this error, the only one that solved it was Lura toon

**Comment by nomaxsnx** [comment]
Please open Issues back up, as nothing has been fixed

**Comment by Norsze** [comment]
You can just tap **filter** and select a sort order and it will display all
