### ISSUE TITLE
Bato.to: Manga opened from URL are recognized as different entries

### ISSUE THREAD

**Issue by Bartuzen** [keiyoushi/tachiyomi-extensions-source#8145]
### Source information

Bato.to 1.4.49

### Source language

Multi

### Steps to reproduce

1. Find a manga from Bato.to in Mihon and add it to the library
2. Open a browser and find the same series on the Bato.to website
3. Click `Open in app` and select Mihon

### Expected behavior

We should be navigated to the entry that was added to library.

### Actual behavior

Mihon detects them as separate entries, and allows adding both to the library.

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 15

### Other details

In the database, the URL of the entry added in Mihon starts with `/series/`, while the other one starts with `https://xbato.net/series/`. The URL should be trimmed to remove the domain name.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MikeZeDev** [comment]
Dumb remark : Wouldn't that be fixed by migrating Bato to Bato ? 

Old bato/Kalot/mangabat where using different domains so manga id was forced to be the full url. Since its not the case now perhaps migrating will fix the problem.

**Comment by Bartuzen** [comment]
I'm not referring to old entries. I installed Mihon and followed the steps above today from scratch. Migrating would fix the issue for that entry, but the problem would still occur for new ones.

**Comment by vetleledaal** [comment]
I would say this is a bug. It stores the absolute URL in the internal database when it should use the relative URL:

![Image](https://github.com/user-attachments/assets/2214122e-7f08-4181-a020-eab0c8f15b76)

**Comment by cuong-tran** [comment]
~~@vetleledaal how do you view the database like that?~~
I got it.

**Comment by Bartuzen** [comment]
> [@vetleledaal](https://github.com/vetleledaal) how do you view the database like that?

It's in Android Studio's App Inspection tab.

**Comment by aranyeren** [comment]
The issue is not only restricted to bato 
It happens with other extensions too

We need a solution!

**Comment by Smol-Ame** [comment]
@aranyeren come to the Keiyoushi Discord support channel for troubleshooting for whatever other extensions are doing this instead of commenting unnecessarily.
